project_id = "yuzioyvuvbuyftgxrczx"

[functions.analyze-resumes]
verify_jwt = false

[functions.check-analysis-status]
verify_jwt = false

[functions.send-lead-to-marq]
verify_jwt = false

[functions.hr-hub-webhook]
verify_jwt = false

[functions.hub-login]
verify_jwt = false

[functions.exchange-hub-token]
verify_jwt = false

[functions.send-lead-to-rdstation]
verify_jwt = false
